
networks:
  app_network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tubeflow-backend
    working_dir: /app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY=${JWT_EXPIRY}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - REFRESH_EXPIRY=${REFRESH_EXPIRY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    networks:
      - app_network

  db:
    image: postgres
    container_name: tubeflow-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mohak
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=youtube
    ports:
      - "5432:5432"
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: tubeflow-redis
    ports:
      - "6379:6379"
    networks:
      - app_network

volumes:
  postgres-data:
