name = "api"
main = "src/index.ts"
compatibility_date = "2024-11-20"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNGFhMmFmZjMtZWEzNC00NTJjLWJlNWUtMDE3ODg0YjhlYTc2IiwidGVuYW50X2lkIjoiZmQ4OTk3MDA4ZDJhMDU1MTVlNTk0YjFlM2U2NDM1Y2M2OTcwNWVmMmE4MWY0MjNjZTExMmExYzczNjNlOWNmYiIsImludGVybmFsX3NlY3JldCI6IjRlYjk3Y2Y3LTgyMjYtNDY1ZS04MDFkLWMyYjdkZTIwOTlkMiJ9.DGYQRXBEutMlT-47SfkiIWaWPldomvKdRDVrP0FG60Y"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1